# Generated by Django 5.0 on 2023-12-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('repo', 'branch', 'path')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=16)),
                ('end', models.CharField(blank=True, max_length=16, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komment.githubcode')),
            ],
        ),
    ]
