# Generated by Django 5.0 on 2023-12-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='githubcode',
            name='id',
        ),
        migrations.AddField(
            model_name='githubcode',
            name='code_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='komment.code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komment.code'),
        ),
    ]
