# Generated by Django 5.0 on 2023-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komment', '0002_code_remove_githubcode_id_githubcode_code_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubcode',
            name='branch',
            field=models.CharField(default='main', max_length=100),
        ),
    ]
